version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - BREWCTL_IS_PROD=false
      - BREWCTL_SCALE_MAC_ADDRESS=${BREWCTL_SCALE_MAC_ADDRESS}
      - BREWCTL_INFLUXDB_TOKEN=${BREWCTL_INFLUXDB_TOKEN}
      - BREWCTL_INFLUXDB_URL=${BREWCTL_INFLUXDB_URL}
      - BREWCTL_INFLUXDB_ORG=${BREWCTL_INFLUXDB_ORG}
      - BREWCTL_VALVE_INTERVAL_SECONDS=${BREWCTL_VALVE_INTERVAL_SECONDS}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      - BREWCTL_FRONTEND_API_URL=${BREWCTL_FRONTEND_API_URL}
      - BREWCTL_IS_PROD=false
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src