version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - COLDBREW_IS_PROD=false
      - COLDBREW_SCALE_MAC_ADDRESS=${COLDBREW_SCALE_MAC_ADDRESS}
      - COLDBREW_INFLUXDB_TOKEN=${COLDBREW_INFLUXDB_TOKEN}
      - COLDBREW_INFLUXDB_URL=${COLDBREW_INFLUXDB_URL}
      - COLDBREW_INFLUXDB_ORG=${COLDBREW_INFLUXDB_ORG}
      - COLDBREW_VALVE_INTERVAL_SECONDS=${COLDBREW_VALVE_INTERVAL_SECONDS}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      - COLDBREW_FRONTEND_API_URL=${COLDBREW_FRONTEND_API_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src