version: '3.8'
services:
  app:
    build: .
    environment:
      - COLDBREW_IS_PROD=false
      - COLDBREW_SCALE_MAC_ADDRESS=${COLDBREW_SCALE_MAC_ADDRESS}
      - COLDBREW_INFLUXDB_TOKEN=${COLDBREW_INFLUXDB_TOKEN}
      - COLDBREW_INFLUXDB_URL=${COLDBREW_INFLUXDB_URL}
      - COLDBREW_INFLUXDB_ORG=${COLDBREW_INFLUXDB_ORG}
      - COLDBREW_VALVE_INTERVAL_SECONDS=${COLDBREW_VALVE_INTERVAL_SECONDS}
      - COLDBREW_FRONTEND_API_URL=${COLDBREW_FRONTEND_API_URL}
    ports:
      - "8000:8000"
